// Mapping of industries to their parent sectors based on Yahoo Finance classification
export const INDUSTRY_TO_SECTOR: Record<string, string> = {
  // Basic Materials
  'Other Industrial Metals & Mining': 'Basic Materials',
  'Specialty Chemicals': 'Basic Materials',
  'Silver': 'Basic Materials',
  'Gold': 'Basic Materials',
  'Building Materials': 'Basic Materials',
  'Paper & Paper Products': 'Basic Materials',
  'Steel': 'Basic Materials',
  'Aluminum': 'Basic Materials',
  'Copper': 'Basic Materials',
  'Chemicals': 'Basic Materials',
  'Coking Coal': 'Basic Materials',
  
  // Communication Services
  'Internet Content & Information': 'Communication Services',
  'Entertainment': 'Communication Services',
  'Telecom Services': 'Communication Services',
  'Electronic Gaming & Multimedia': 'Communication Services',
  'Broadcasting': 'Communication Services',
  'Publishing': 'Communication Services',
  'Advertising Agencies': 'Communication Services',
  
  // Consumer Cyclical
  'Lodging': 'Consumer Cyclical',
  'Internet Retail': 'Consumer Cyclical',
  'Auto Manufacturers': 'Consumer Cyclical',
  'Apparel Retail': 'Consumer Cyclical',
  'Travel Services': 'Consumer Cyclical',
  'Restaurants': 'Consumer Cyclical',
  'Department Stores': 'Consumer Cyclical',
  'Packaging & Containers': 'Consumer Cyclical',
  'Footwear & Accessories': 'Consumer Cyclical',
  'Home Improvement Retail': 'Consumer Cyclical',
  'Leisure': 'Consumer Cyclical',
  'Auto & Truck Dealerships': 'Consumer Cyclical',
  'Auto Parts': 'Consumer Cyclical',
  'Luxury Goods': 'Consumer Cyclical',
  'Apparel Manufacturing': 'Consumer Cyclical',
  'Gambling': 'Consumer Cyclical',
  'Residential Construction': 'Consumer Cyclical',
  'Furnishings, Fixtures & Appliances': 'Consumer Cyclical',
  'Specialty Retail': 'Consumer Cyclical',
  'Recreational Vehicles': 'Consumer Cyclical',
  
  // Consumer Defensive
  'Packaged Foods': 'Consumer Defensive',
  'Discount Stores': 'Consumer Defensive',
  'Household & Personal Products': 'Consumer Defensive',
  'Beverages - Non-Alcoholic': 'Consumer Defensive',
  'Grocery Stores': 'Consumer Defensive',
  'Beverages - Brewers': 'Consumer Defensive',
  'Tobacco': 'Consumer Defensive',
  'Beverages - Wineries & Distilleries': 'Consumer Defensive',
  'Food Distribution': 'Consumer Defensive',
  'Personal Services': 'Consumer Defensive',
  'Confectioners': 'Consumer Defensive',
  'Farm Products': 'Consumer Defensive',
  'Education & Training Services': 'Consumer Defensive',
  
  // Energy
  'Oil & Gas Integrated': 'Energy',
  'Uranium': 'Energy',
  'Oil & Gas E&P': 'Energy',
  'Oil & Gas Midstream': 'Energy',
  'Oil & Gas Equipment & Services': 'Energy',
  'Oil & Gas Refining & Marketing': 'Energy',
  'Oil & Gas Drilling': 'Energy',
  'Thermal Coal': 'Energy',
  
  // Financial Services
  'Credit Services': 'Financial Services',
  'Financial Data & Stock Exchanges': 'Financial Services',
  'Banks - Diversified': 'Financial Services',
  'Insurance - Diversified': 'Financial Services',
  'Capital Markets': 'Financial Services',
  'Insurance - Property & Casualty': 'Financial Services',
  'Banks - Regional': 'Financial Services',
  'Asset Management': 'Financial Services',
  'Insurance - Life': 'Financial Services',
  'Insurance - Specialty': 'Financial Services',
  'Insurance - Reinsurance': 'Financial Services',
  'Mortgage Finance': 'Financial Services',
  'Financial Conglomerates': 'Financial Services',
  'Insurance Brokers': 'Financial Services',
  'Shell Companies': 'Financial Services',
  
  // Healthcare
  'Drug Manufacturers - Specialty & Generic': 'Healthcare',
  'Medical Devices': 'Healthcare',
  'Diagnostics & Research': 'Healthcare',
  'Medical Instruments & Supplies': 'Healthcare',
  'Biotechnology': 'Healthcare',
  'Drug Manufacturers - General': 'Healthcare',
  'Health Information Services': 'Healthcare',
  'Medical Care Facilities': 'Healthcare',
  'Healthcare Plans': 'Healthcare',
  'Pharmaceutical Retailers': 'Healthcare',
  'Medical Distribution': 'Healthcare',
  
  // Industrials
  'Airlines': 'Industrials',
  'Integrated Freight & Logistics': 'Industrials',
  'Specialty Business Services': 'Industrials',
  'Specialty Industrial Machinery': 'Industrials',
  'Conglomerates': 'Industrials',
  'Electrical Equipment & Parts': 'Industrials',
  'Aerospace & Defense': 'Industrials',
  'Farm & Heavy Construction Machinery': 'Industrials',
  'Industrial Distribution': 'Industrials',
  'Rental & Leasing Services': 'Industrials',
  'Engineering & Construction': 'Industrials',
  'Railroads': 'Industrials',
  'Building Products & Equipment': 'Industrials',
  'Waste Management': 'Industrials',
  'Security & Protection Services': 'Industrials',
  'Consulting Services': 'Industrials',
  'Staffing & Employment Services': 'Industrials',
  'Tools & Accessories': 'Industrials',
  'Pollution & Treatment Controls': 'Industrials',
  'Trucking': 'Industrials',
  'Marine Shipping': 'Industrials',
  'Business Equipment & Supplies': 'Industrials',
  'Infrastructure Operations': 'Industrials',
  
  // Real Estate
  'REIT - Industrial': 'Real Estate',
  'REIT - Healthcare Facilities': 'Real Estate',
  'REIT - Residential': 'Real Estate',
  'REIT - Specialty': 'Real Estate',
  'REIT - Office': 'Real Estate',
  'Real Estate Services': 'Real Estate',
  'REIT - Retail': 'Real Estate',
  'Real Estate - Development': 'Real Estate',
  'Real Estate - Diversified': 'Real Estate',
  'REIT - Diversified': 'Real Estate',
  'REIT - Mortgage': 'Real Estate',
  'REIT - Hotel & Motel': 'Real Estate',
  
  // Technology
  'Information Technology Services': 'Technology',
  'Semiconductors': 'Technology',
  'Software - Application': 'Technology',
  'Consumer Electronics': 'Technology',
  'Software - Infrastructure': 'Technology',
  'Semiconductor Equipment & Materials': 'Technology',
  'Scientific & Technical Instruments': 'Technology',
  'Electronic Components': 'Technology',
  'Computer Hardware': 'Technology',
  'Communication Equipment': 'Technology',
  'Electronics & Computer Distribution': 'Technology',
  'Solar': 'Technology',
  
  // Utilities
  'Utilities - Regulated Electric': 'Utilities',
  'Utilities - Independent Power Producers': 'Utilities',
  'Utilities - Diversified': 'Utilities',
  'Utilities - Renewable': 'Utilities',
  'Utilities - Regulated Water': 'Utilities',
  'Utilities - Regulated Gas': 'Utilities',
};

// Get all unique sectors
export const SECTOR_GROUPS = {
  'Basic Materials': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Basic Materials'),
  'Communication Services': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Communication Services'),
  'Consumer Cyclical': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Consumer Cyclical'),
  'Consumer Defensive': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Consumer Defensive'),
  'Energy': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Energy'),
  'Financial Services': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Financial Services'),
  'Healthcare': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Healthcare'),
  'Industrials': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Industrials'),
  'Real Estate': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Real Estate'),
  'Technology': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Technology'),
  'Utilities': Object.keys(INDUSTRY_TO_SECTOR).filter(ind => INDUSTRY_TO_SECTOR[ind] === 'Utilities'),
  'N/A': ['N/A'], // Catch-all for unclassified industries
};

// Get all industries (for master list)
export const ALL_INDUSTRIES = [
  ...Object.keys(INDUSTRY_TO_SECTOR).sort(),
  'N/A', // Catch-all
];
