// Standard industry list for portfolio diversification
export const MASTER_INDUSTRIES = [
  'Hotels, Restaurants & Leisure',
  'Diversified Consumer Services',
  'Consumer Products',
  'Textiles, Apparel & Luxury Goods',
  'Pharmaceuticals',
  'Airlines',
  'Life Sciences Tools & Services',
  'Financial Services',
  'Retail',
  'Technology',
  'Professional Services',
  'Health Care',
  'Biotechnology',
  'Packaging',
  'Machinery',
  'Real Estate',
  'Semiconductors',
  'Electrical Equipment',
  'Communications',
  'Media',
  'Construction',
  'Distributors',
  'Automobiles',
  'Aerospace & Defense',
  'Telecommunication',
  'Beverages',
  'Building',
  'Utilities',
  'Auto Components',
  'Energy',
];
