// Standard country list for portfolio diversification
export const MASTER_COUNTRIES = [
  'United States',
  'China',
  'Japan',
  'United Kingdom',
  'Germany',
  'France',
  'India',
  'Canada',
  'South Korea',
  'Italy',
  'Brazil',
  'Australia',
  'Spain',
  'Mexico',
  'Indonesia',
  'Netherlands',
  'Saudi Arabia',
  'Switzerland',
  'Turkey',
  'Taiwan',
  'Poland',
  'Belgium',
  'Thailand',
  'Argentina',
  'Sweden',
  'Ireland',
  'Norway',
  'Israel',
  'Singapore',
  'Denmark',
  'United Arab Emirates',
  'Hong Kong',
  'Malaysia',
  'Philippines',
  'South Africa',
  'Egypt',
  'Pakistan',
  'Chile',
  'Finland',
  'Colombia',
  'Romania',
  'Czech Republic',
  'Portugal',
  'New Zealand',
  'Greece',
  'Peru',
  'Vietnam',
  'Hungary',
  'Luxembourg',
  'Austria',
];
